import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.*;import ghidra.program.model.listing.*;import ghidra.program.model.symbol.*;import ghidra.program.model.pcode.Varnode;
import java.util.*;
import java.nio.charset.StandardCharsets;
import com.google.gson.*;
public class CampaignTypes extends GhidraScript {
 DataType type(String path)throws Exception{var t=currentProgram.getDataTypeManager().getDataType(path);if(t==null)t=BuiltInDataTypeManager.getDataTypeManager().getDataType(path);if(t==null)throw new Exception("Unknown type "+path);return t;}
 VariableStorage storage(JsonObject value,DataType type)throws Exception{var s=value.getAsJsonObject("storage");VariableStorage result;if(s.has("register")){var reg=currentProgram.getRegister(s.get("register").getAsString());if(reg==null)throw new Exception("Unknown register");result=new VariableStorage(currentProgram,reg);}else result=new VariableStorage(currentProgram,new Varnode(currentProgram.getAddressFactory().getStackSpace().getAddress(s.get("stack").getAsLong()),type.getLength()));if(result.size()!=type.getLength())throw new Exception("Storage/type width mismatch");return result;}
 public void run()throws Exception{
  var config=JsonParser.parseString(new String(Base64.getDecoder().decode(getScriptArgs()[0]),StandardCharsets.UTF_8)).getAsJsonObject();var plan=config.getAsJsonObject("plan");
  if(!currentProgram.getExecutableSHA256().equals(plan.getAsJsonObject("identity").get("digest").getAsString()))throw new Exception("Digest mismatch");
  String id=plan.get("id").getAsString();var journal=currentProgram.getOptions("GhidraManagerCampaign");if(!journal.getString(id,"").isEmpty())throw new Exception("Reconcile existing type transaction");
  int tx=currentProgram.startTransaction("Ghidra Manager layouts "+id);boolean committed=false;
  try{for(var e:plan.getAsJsonArray("changes")){monitor.checkCancelled();var c=e.getAsJsonObject();String kind=c.get("kind").getAsString();
    if(kind.equals("compiler_model")){String name=c.get("name").getAsString();if(currentProgram.getCompilerSpec().getCallingConvention(name)!=null)throw new Exception("Existing compiler model conflicts");new ghidra.program.database.SpecExtension(currentProgram).addReplaceCompilerSpecExtension(c.get("xml").getAsString(),monitor);
    }else if(kind.equals("abi")){var f=getFunctionAt(toAddr(c.get("address").getAsString()));if(f==null)throw new Exception("Missing ABI function");String convention=c.get("convention").getAsString();if(currentProgram.getCompilerSpec().getCallingConvention(convention)==null)throw new Exception("Unknown calling convention");var params=new ArrayList<Variable>();for(var item:c.getAsJsonArray("parameters")){var p=item.getAsJsonObject();var t=type(p.get("type").getAsString());var st=storage(p,t);for(var old:params)if(st.intersects(old.getVariableStorage()))throw new Exception("Overlapping parameter storage");params.add(new ParameterImpl(p.get("name").getAsString(),t,st,currentProgram));}var r=c.getAsJsonObject("return");var rt=type(r.get("type").getAsString());var ret=rt instanceof VoidDataType?new ReturnParameterImpl(rt,currentProgram):new ReturnParameterImpl(rt,storage(r,rt),currentProgram);f.updateFunction(convention,ret,Function.FunctionUpdateType.CUSTOM_STORAGE,true,SourceType.USER_DEFINED,params.toArray(new Variable[0]));f.setVarArgs(c.get("varargs").getAsBoolean());f.setNoReturn(c.get("noreturn").getAsBoolean());
    }else if(kind.equals("structure")){String path=c.get("path").getAsString();if(currentProgram.getDataTypeManager().getDataType(path)!=null)throw new Exception("Existing structure conflicts");int split=path.lastIndexOf('/');var s=new StructureDataType(new CategoryPath(split==0?"/":path.substring(0,split)),path.substring(split+1),c.get("length").getAsInt());
     for(var field:c.getAsJsonArray("fields")){var f=field.getAsJsonObject();var t=type(f.get("type").getAsString());int length=f.get("length").getAsInt();if(t.getLength()!=length)throw new Exception("Field type extent mismatch");s.replaceAtOffset(f.get("offset").getAsInt(),t,length,f.get("name").getAsString(),null);}currentProgram.getDataTypeManager().addDataType(s,DataTypeConflictHandler.KEEP_HANDLER);
    }else if(kind.equals("data_type")){var a=toAddr(c.get("address").getAsString());var t=type(c.get("type").getAsString());int length=c.get("length").getAsInt();if(t.getLength()!=length)throw new Exception("Data extent mismatch");var end=a.add(length-1);
     for(int n=0;n<length;n++){var at=a.add(n);if(getInstructionContaining(at)!=null||getFunctionContaining(at)!=null)throw new Exception("Data overlaps code");var d=currentProgram.getListing().getDefinedDataContaining(at);if(d!=null&&(d.getMinAddress().compareTo(a)<0||d.getMaxAddress().compareTo(end)>0))throw new Exception("Partial data overlap");}clearListing(a,end);createData(a,t);
    }else throw new Exception("Unsupported layout operation");
   }journal.setString(id,"applied");committed=true;
  }finally{currentProgram.endTransaction(tx,committed);}
  var result=new JsonObject();result.addProperty("complete",true);result.addProperty("committed",committed);result.addProperty("transaction",id);java.nio.file.Files.writeString(java.nio.file.Path.of(config.get("output").getAsString()),result.toString());println("CAMPAIGN_RESULT:complete");
 }
}
