import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.*;
import ghidra.program.model.data.*;
import java.util.*;
import java.security.MessageDigest;
import com.google.gson.*;

public class CampaignInventory extends GhidraScript {
 String hash(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}
 public void run()throws Exception{
  var config=JsonParser.parseString(new String(Base64.getDecoder().decode(getScriptArgs()[0]),java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject();
  var result=new JsonObject();var identity=new JsonObject();var locator=currentProgram.getDomainFile().getProjectLocator();if(locator==null)locator=state.getProject().getProjectLocator();
  identity.addProperty("project",locator.getName());identity.addProperty("project_path",java.nio.file.Path.of(locator.getLocation(),locator.getName()+".gpr").toString());
  identity.addProperty("program_path",currentProgram.getDomainFile().getPathname());identity.addProperty("digest",currentProgram.getExecutableSHA256());
  identity.addProperty("language",currentProgram.getLanguageID().toString());identity.addProperty("compiler",currentProgram.getCompilerSpec().getCompilerSpecID().toString());
  identity.addProperty("image_base",currentProgram.getImageBase().toString());identity.addProperty("format",currentProgram.getExecutableFormat());
  var spaces=new JsonArray();for(var a:currentProgram.getAddressFactory().getAddressSpaces())spaces.add(a.getName());identity.add("address_spaces",spaces);result.add("identity",identity);var conventions=new JsonArray();for(var model:currentProgram.getCompilerSpec().getCallingConventions())conventions.add(model.getName());result.add("calling_conventions",conventions);
  var options=new JsonObject();for(String group:currentProgram.getOptionsNames()){if(group.equals("GhidraManagerCampaign"))continue;var o=currentProgram.getOptions(group);var v=new JsonObject();for(String name:o.getOptionNames()){if(group.equals("Program Information")&&name.startsWith("Analysis Times."))continue;v.addProperty(name,o.getValueAsString(name));}options.add(group,v);}result.add("configuration",options);var transactions=new JsonObject();var journal=currentProgram.getOptions("GhidraManagerCampaign");for(String key:journal.getOptionNames())transactions.addProperty(key,journal.getString(key,""));result.add("transactions",transactions);
  var functions=new JsonArray();var fs=currentProgram.getFunctionManager().getFunctions(true);
  while(fs.hasNext()) {monitor.checkCancelled();var f=fs.next();var row=new JsonObject();row.addProperty("address",f.getEntryPoint().toString());row.addProperty("name",f.getName());row.addProperty("namespace",f.getParentNamespace().getName(true));row.addProperty("signature",f.getSignature().toString());row.addProperty("body",f.getBody().toString());var ranges=new JsonArray();for(var range:f.getBody().getAddressRanges()){var pair=new JsonArray();pair.add(range.getMinAddress().toString());pair.add(range.getMaxAddress().toString());ranges.add(pair);}row.add("body_ranges",ranges);row.addProperty("source",f.getSymbol().getSource().toString());row.addProperty("external",f.isExternal());row.addProperty("thunk",f.isThunk());
   var digest=MessageDigest.getInstance("SHA-256");var codeDigest=MessageDigest.getInstance("SHA-256");var shape=new StringBuilder();var ins=currentProgram.getListing().getInstructions(f.getBody(),true);int count=0;var flows=new JsonArray();var referenced=new TreeSet<String>();while(ins.hasNext()){var i=ins.next();count++;for(var ref:i.getReferencesFrom())referenced.add(ref.getToAddress().toString());digest.update(i.getAddress().toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));digest.update(i.getBytes());codeDigest.update(i.getBytes());shape.append(i.getMnemonicString()).append(":").append(i.getNumOperands()).append(";");if(i.getFlowType().isFlow()||i.getFlowOverride()!=FlowOverride.NONE){var flow=new JsonObject();flow.addProperty("address",i.getAddress().toString());flow.addProperty("computed",i.getFlowType().isComputed());flow.addProperty("override",i.getFlowOverride().toString());var refs=new JsonArray();for(var ref:i.getReferencesFrom())if(ref.getReferenceType().isFlow())refs.add(ref.getToAddress()+":"+ref.getReferenceType());flow.add("targets",refs);flows.add(flow);}}
   row.addProperty("code_hash",HexFormat.of().formatHex(codeDigest.digest()));row.addProperty("shape_hash",hash(shape.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8)));row.addProperty("instruction_count",count);row.addProperty("byte_hash",HexFormat.of().formatHex(digest.digest()));row.add("flows",flows);var references=new JsonArray();for(var a:referenced)references.add(a);row.add("references",references);row.addProperty("comment",f.getComment());
   var abi=new JsonObject();abi.addProperty("convention",f.getCallingConventionName());abi.addProperty("return_type",f.getReturnType().getPathName());abi.addProperty("return_storage",f.getReturn().getVariableStorage().toString());abi.addProperty("varargs",f.hasVarArgs());abi.addProperty("noreturn",f.hasNoReturn());abi.addProperty("custom_storage",f.hasCustomVariableStorage());var parameters=new JsonArray();for(var param:f.getParameters()){var item=new JsonObject();item.addProperty("type",param.getDataType().getPathName());item.addProperty("storage",param.getVariableStorage().toString());parameters.add(item);}abi.add("parameters",parameters);row.add("abi",abi);
   var vars=new JsonArray();for(var v:f.getAllVariables()){var x=new JsonObject();x.addProperty("name",v.getName());x.addProperty("type",v.getDataType().getPathName());x.addProperty("storage",v.getVariableStorage().toString());x.addProperty("parameter",v instanceof Parameter);vars.add(x);}row.add("variables",vars);
   var calledAddresses=new TreeSet<String>();for(var c:f.getCalledFunctions(monitor))calledAddresses.add(c.getEntryPoint().toString());var callees=new JsonArray();for(var address:calledAddresses)callees.add(address);row.add("callees",callees);functions.add(row);
  }result.add("functions",functions);
  var blocks=new JsonArray();for(var block:currentProgram.getMemory().getBlocks()){var b=new JsonObject();b.addProperty("start",block.getStart().toString());b.addProperty("end",block.getEnd().toString());b.addProperty("initialized",block.isInitialized());if(block.isInitialized()){var digest=MessageDigest.getInstance("SHA-256");byte[] chunk=new byte[65536];long offset=0;while(offset<block.getSize()){monitor.checkCancelled();int count=(int)Math.min(chunk.length,block.getSize()-offset);block.getBytes(block.getStart().add(offset),chunk,0,count);digest.update(chunk,0,count);offset+=count;}b.addProperty("hash",HexFormat.of().formatHex(digest.digest()));}blocks.add(b);}result.add("memory",blocks);
  var symbols=new JsonArray();var si=currentProgram.getSymbolTable().getAllSymbols(true);while(si.hasNext()){monitor.checkCancelled();var s=si.next();var row=new JsonObject();row.addProperty("id",s.getID());row.addProperty("address",s.getAddress().toString());row.addProperty("name",s.getName());row.addProperty("kind",s.getSymbolType().toString());row.addProperty("namespace",s.getParentNamespace().getName(true));row.addProperty("primary",s.isPrimary());symbols.add(row);}result.add("symbols",symbols);
  var types=new JsonArray();var ti=currentProgram.getDataTypeManager().getAllDataTypes();while(ti.hasNext()){monitor.checkCancelled();var t=ti.next();var row=new JsonObject();row.addProperty("path",t.getPathName());row.addProperty("length",t.getLength());row.addProperty("definition",t.toString());if(t instanceof Structure){var fields=new JsonArray();for(var field:((Structure)t).getDefinedComponents()){var item=new JsonObject();item.addProperty("offset",field.getOffset());item.addProperty("length",field.getLength());item.addProperty("type",field.getDataType().getPathName());item.addProperty("name",field.getFieldName());fields.add(item);}row.add("fields",fields);}types.add(row);}result.add("types",types);
  var data=new JsonArray();var strings=new JsonArray();var di=currentProgram.getListing().getDefinedData(true);while(di.hasNext()){var d=di.next();var item=new JsonObject();item.addProperty("address",d.getAddress().toString());item.addProperty("length",d.getLength());item.addProperty("type",d.getDataType().getPathName());data.add(item);if(d.hasStringValue()){var row=new JsonObject();row.addProperty("address",d.getAddress().toString());row.addProperty("value",String.valueOf(d.getValue()));strings.add(row);}}result.add("strings",strings);result.add("data",data);
  var databases=new JsonArray();for(var file:ghidra.feature.fid.db.FidFileManager.getInstance().getFidFiles()){var row=new JsonObject();row.addProperty("name",file.getName());row.addProperty("path",file.getPath());row.addProperty("active",file.isActive());row.addProperty("compatible_language",file.canProcessLanguage(currentProgram.getLanguage()));databases.add(row);}result.add("fid_databases",databases);
  result.addProperty("schema_version",1);result.addProperty("collector_version",8);result.addProperty("complete",true);java.nio.file.Files.writeString(java.nio.file.Path.of(config.get("output").getAsString()),result.toString());println("CAMPAIGN_RESULT:complete");
 }
}
